---
name: module4_task3

on:
  push:
    branches: [master, main]
    tags:
      - "*.*.*"
  schedule:
    - cron: "0 0 * * *"

  pull_request:
    types: [opened, reopened, edited, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Execute the setup.sh file
        working-directory: module4_task3
        run: ./setup.sh

      - name: Create and test awesome:build image
        working-directory: module4_task3
        run: |
          make build-docker
          echo "$PATH"
          docker images
          docker run --rm -v $(pwd):/app awesome:build make lint
          make docker-tests
      - name: Create a docker image
        working-directory: module4_task3
        run: |
          make build-docker
          docker run --rm -v $(pwd):/app awesome:build make clean
          docker run --rm -v $(pwd):/app awesome:build make build
          docker run --rm -v $(pwd):/app awesome:build make unit-tests
          docker run --rm -v $(pwd):/app awesome:build make integration-tests
          ls -la
          docker images
