---
name: module3_task3
on:
  schedule:
    - cron: "* * * * *"
  push:
    branches:
      - 'main'
      - 'master'
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Check setup file
        run: make lint -C module3_task3/

      - name: Install tools
        run: |
          cd module3_task3
          sudo ./setup.sh
      - name: Build
        run: make build -C module3_task3/

      - name: Validate
        run: make validate -C module3_task3/

      - name: Unit testing
        run: make unit-tests -C module3_task3/

      - name: Integration testing
        run: make integration-tests -C module3_task3/

      - name: Package
        run: make package -C module3_task3/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            module3_task3/DEPLOY.md
            module3_task3/awesome-website.zip
...