---
name: module4_task0

on:
  push:
    branches: [master, main]
    tags:
      - '*.*.*'
  schedule:
    - cron: '0 0 * * *'

  pull_request:
    types: [opened, reopened, edited, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Execute the script setup.sh
        run: |
          cd module4_task0/
          ./setup.sh
      - name: Run markdownlint on markdown files
        run: make lint -C module4_task0/

      - name: Build the application
        run: make build -C module4_task0/

      - name: Archive the dist folder inside a zip file
        run: make package -C module4_task0/

      - name: Run additional make rules
        run: |
          make unit-tests -C module4_task0/
          make integration-tests -C module4_task0/
          make validate -C module4_task0/
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Archive awesome-website.zip as artifact
          path: module4_task0/awesome-website.zip

      - name: Create a GitHub Release
        uses: softprops/action-gh-release@v1
        # if: github.event.pull_request
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            module4_task0/awesome-website.zip
            module4_task0/DEPLOY.md

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: 'module4_task0/dist'
          production-branch: master
          github-token: ${{ secrets.REPO_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1